# Pre-commit configuration for Threadspace
# See https://pre-commit.com for more information

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: check-merge-conflict
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: detect-private-key

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3
        args: [--line-length=80]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: [--profile=black, --line-length=80]

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies:
        -   flake8-docstrings
        -   flake8-bugbear
        -   flake8-comprehensions
        -   flake8-simplify
        args: [--max-line-length=80]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        additional_dependencies:
        -   types-all
        args: [--ignore-missing-imports]

-   repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        args: [-ll, -r]

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.4.0
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]

-   repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
    -   id: docformatter
        args: [--in-place, --wrap-summaries=80, --wrap-descriptions=80]

-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [push]

    -   id: system-check
        name: System Health Check
        entry: python -m guardian.system_init --health-check
        language: system
        pass_filenames: false
        always_run: true
        stages: [push]

# Custom settings
default_language_version:
    python: python3.8

default_stages: [commit, push]

ci:
    autofix_commit_msg: 'style: auto fixes from pre-commit hooks'
    autoupdate_commit_msg: 'chore: pre-commit autoupdate'
    skip: []
    submodules: false

# File patterns to exclude
exclude: |
    (?x)(
        ^docs/|
        ^.venv/|
        ^venv/|
        ^build/|
        ^dist/|
        .pytest_cache/|
        __pycache__/|
        \.git/|
        \.eggs/|
        \.tox/|
        \.coverage
    )
